---
name: consats

director_uuid: BOSH_DIRECTOR_UUID # REPLACE ME

releases:
- name: consul
  version: CONSUL_RELEASE_VERSION # REPLACE ME

stemcells:
- alias: default
  os: ubuntu-trusty
  version: STEMCELL_VERSION # REPLACE ME

instance_groups:
- name: acceptance-tests
  instances: 1
  lifecycle: errand
  azs: [BOSH_ERRAND_CLOUD_CONFIG_NETWORK_AZ] # REPLACE ME
  vm_type: m3.medium
  vm_extensions: [10GB_ephemeral_disk]
  stemcell: default
  networks:
  - name: BOSH_ERRAND_CLOUD_CONFIG_NETWORK_NAME # REPLACE ME
    static_ips: [BOSH_ERRAND_CLOUD_CONFIG_NETWORK_STATIC_IP] # REPLACE ME
  jobs:
  - name: acceptance-tests
    release: consul

properties:
  consul:
    acceptance_tests:
      aws:
        access_key_id: AWS_ACCESS_KEY_ID # REPLACE ME
        secret_access_key: AWS_SECRET_ACCESS_KEY # REPLACE ME
        region: AWS_REGION # REPLACE ME
        default_key_name: bosh
        default_security_groups:
        - AWS_SECURITY_GROUP_NAME # REPLACE ME
        subnets:
        - id: AWS_SUBNET_ID # REPLACE ME
          range: AWS_SUBNET_RANGE # REPLACE ME
          az: AWS_SUBNET_AZ # REPLACE ME
          security_group: AWS_SUBNET_SECURITY_GROUP # REPLACE ME
        cloud_config_subnets:
        - id: AWS_CLOUD_CONFIG_SUBNET_ID # REPLACE ME
          range: AWS_CLOUD_CONFIG_SUBNET_RANGE # REPLACE ME
          az: AWS_CLOUD_CONFIG_SUBNET_AZ # REPLACE ME
          security_group: AWS_CLOUD_CONFIG_SUBNET_SECURITY_GROUP # REPLACE ME
      bosh:
        target: BOSH_DIRECTOR # REPLACE ME
        username: BOSH_USER # REPLACE ME
        password: BOSH_PASSWORD # REPLACE ME
        director_ca_cert: BOSH_DIRECTOR_CA_CERT # REPLACE ME
        errand:
         network:
           name: BOSH_ERRAND_CLOUD_CONFIG_NETWORK_NAME # REPLACE ME
           static_ip: BOSH_ERRAND_CLOUD_CONFIG_NETWORK_STATIC_IP # REPLACE ME
           az: BOSH_ERRAND_CLOUD_CONFIG_NETWORK_AZ # REPLACE ME
         default_persistent_disk_type: BOSH_ERRAND_CLOUD_CONFIG_DEFAULT_PERSISTENT_DISK_TYPE # REPLACE ME
         default_vm_type: BOSH_ERRAND_CLOUD_CONFIG_DEFAULT_VM_TYPE # REPLACE ME
      registry:
        username: REGISTRY_USERNAME # REPLACE ME
        password: REGISTRY_PASSWORD # REPLACE ME
        host: REGISTRY_HOST # REPLACE ME
        port: 25777
      parallel_nodes: 1
      consul_release_version: CONSUL_RELEASE_VERSION # REPLACE ME

update:
  serial: true
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-180000
  update_watch_time: 1000-180000
